/**
 * Roles del sistema, **exactamente como los nombra el central**.
 *
 * ⚠️ El valor lleva espacios porque así está en `personas.role`. Comparar
 * contra una versión con guiones o guiones bajos no coincide con nada, y el
 * fallo es silencioso: el usuario simplemente no ve la opción.
 *
 * Generado desde la base el 2026-08-14 — 41 roles. La versión anterior
 * tenía 13 e incluía `DIRECTIVO`, que **no existe**: cualquier chequeo
 * contra él daba siempre falso y el permiso no se podía delegar.
 */
export enum ROLES {
  ADMIN = 'ADMIN',
  ANALISIS_CONTABLE = 'ANALISIS CONTABLE',
  ANALISIS_DE_CAJA = 'ANALISIS DE CAJA',
  ANALISIS_DE_VENTA = 'ANALISIS DE VENTA',
  ANALISIS_FINANCIERO = 'ANALISIS FINANCIERO',
  CAMBIAR_COTIZACION = 'CAMBIAR COTIZACION',
  CANCELACION_DE_VENTA = 'CANCELACION DE VENTA',
  COMISION_APROBAR = 'COMISION APROBAR',
  COMISION_GESTIONAR = 'COMISION GESTIONAR',
  CREAR_FUNCIONARIOS = 'CREAR FUNCIONARIOS',
  CREAR_INVENTARIO = 'CREAR INVENTARIO',
  CREAR_PRECIOS = 'CREAR PRECIOS',
  CREAR_TRANSFERENCIA = 'CREAR TRANSFERENCIA',
  EDITAR_FUNCIONARIOS = 'EDITAR FUNCIONARIOS',
  EDITAR_PERSONAS = 'EDITAR PERSONAS',
  EDITAR_PRECIOS = 'EDITAR PRECIOS',
  EDITAR_PRODUCTOS = 'EDITAR PRODUCTOS',
  EDITAR_USUARIOS = 'EDITAR USUARIOS',
  PARTICIPAR_DEL_INVENTARIO = 'PARTICIPAR DEL INVENTARIO',
  RECIBIR_PEDIDOS = 'RECIBIR PEDIDOS',
  RRHH_APROBAR = 'RRHH APROBAR',
  RRHH_CONFIG = 'RRHH CONFIG',
  RRHH_GESTIONAR = 'RRHH GESTIONAR',
  RRHH_LIQUIDAR = 'RRHH LIQUIDAR',
  RRHH_PAGAR = 'RRHH PAGAR',
  RRHH_VER = 'RRHH VER',
  SOPORTE = 'SOPORTE',
  TESORERIA_CPC_COBRAR = 'TESORERIA CPC COBRAR',
  TESORERIA_CPP_PAGAR = 'TESORERIA CPP PAGAR',
  TESORERIA_GESTIONAR = 'TESORERIA GESTIONAR',
  TESORERIA_VER = 'TESORERIA VER',
  VENTA_TOUCH = 'VENTA TOUCH',
  VER_FUNCIONARIOS = 'VER FUNCIONARIOS',
  VER_INVENTARIO = 'VER INVENTARIO',
  VER_MOVIMIENTO_DE_STOCK = 'VER MOVIMIENTO DE STOCK',
  VER_PERSONAS = 'VER PERSONAS',
  VER_PRE_REGISTRO_FUNCIONARIOS = 'VER PRE REGISTRO FUNCIONARIOS',
  VER_PRECIO_COSTO = 'VER PRECIO COSTO',
  VER_PRODUCTOS = 'VER PRODUCTOS',
  VER_TRANSFERENCIA = 'VER TRANSFERENCIA',
  VER_USUARIOS = 'VER USUARIOS',
}
